services:
  api:
    image: ghcr.io/esther7473/bihar2026_tpt_behiblo:latest
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  streamlit:
    image: ghcr.io/esther7473/bihar2026_tpt_behiblo-streamlit:latest
    ports:
      - "8501:8501"
    depends_on:
      api:
       condition: service_healthy
    networks:
      - monitoring
    environment:
      - PYTHONPATH=/app

  prometheus:
    image: prom/prometheus
    depends_on:
    - api 
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    env_file:
    - .env
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge