services:
  api:
    image: ghcr.io/esther7473/bihar2026_tpt_behiblo:latest
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data
    networks:
      - monitoring

  streamlit:
    image: ghcr.io/esther7473/bihar2026_tpt_behiblo-streamlit:latest
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - monitoring
    environment:
      - PYTHONPATH=/app

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge